const express = require('express')
const app = express()
const bodyParser = require('body-parser')
const morgan = require('morgan')
const router = require('./routes/routes')
const cors = require('cors')
app.use(cors())
app.use(bodyParser.urlencoded({limit: '50mb', extended: false}))
app.use(bodyParser.json({limit: '50mb', extended: true}))
app.use(morgan('dev'))
app.use(router)
const server = app.listen(process.env.PORT || 8080, () => {
    var port = server.address().port
    console.log("Barberros started on " + port)
})
